name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Ci_Verification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
      
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test Backend Service Api 
      working-directory: ./backend
      run: |
        npm ci
        npm run dev
